### ISSUE TITLE
Error Getting Reflective Information

### ISSUE THREAD

**Issue by marlon-ulloa** [wesleyegberto/javaee8-jsf-chat#1]
Hi, I would like that can help me....
I import the project to eclipse, when I run the project, shows the following error:

ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."jsf-chat.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."jsf-chat.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "jsf-chat.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: WFLYSRV0177: Error getting reflective information for class com.github.wesleyegberto.adoptajsr.jsfchat.service.ChatRoom with ClassLoader ModuleClassLoader for Module "deployment.jsf-chat.war:main" from Service Module Loader
	at org.jboss.as.server.deployment.reflect.DeploymentReflectionIndex.getClassIndex(DeploymentReflectionIndex.java:70)
	at org.jboss.as.ee.metadata.MethodAnnotationAggregator.runtimeAnnotationInformation(MethodAnnotationAggregator.java:57)
	at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.handleAnnotations(InterceptorAnnotationProcessor.java:106)
	at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.processComponentConfig(InterceptorAnnotationProcessor.java:91)
	at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.deploy(InterceptorAnnotationProcessor.java:76)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: Ljavax/faces/push/PushContext;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at org.jboss.as.server.deployment.reflect.ClassReflectionIndex.<init>(ClassReflectionIndex.java:72)
	at org.jboss.as.server.deployment.reflect.DeploymentReflectionIndex.getClassIndex(DeploymentReflectionIndex.java:66)
	... 10 more
Caused by: java.lang.ClassNotFoundException: javax.faces.push.PushContext from [Module "deployment.jsf-chat.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	... 15 more

00:16:47,797 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jsf-chat.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jsf-chat.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"jsf-chat.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"jsf-chat.war\"
    Caused by: java.lang.RuntimeException: WFLYSRV0177: Error getting reflective information for class com.github.wesleyegberto.adoptajsr.jsfchat.service.ChatRoom with ClassLoader ModuleClassLoader for Module \"deployment.jsf-chat.war:main\" from Service Module Loader
    Caused by: java.lang.NoClassDefFoundError: Ljavax/faces/push/PushContext;
    Caused by: java.lang.ClassNotFoundException: javax.faces.push.PushContext from [Module \"deployment.jsf-chat.war:main\" from Service Module Loader]"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"jsf-chat.war\".POST_MODULE"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
00:16:47,819 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "jsf-chat.war" (runtime-name : "jsf-chat.war")
00:16:47,821 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."jsf-chat.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."jsf-chat.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "jsf-chat.war"

00:16:47,966 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
00:16:47,967 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
00:16:47,967 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started (with errors) in 3442ms - Started 370 of 617 services (1 services failed or missing dependencies, 399 services are lazy, passive or on-demand)
00:16:47,997 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment jsf-chat.war (runtime-name: jsf-chat.war) in 9ms
00:16:48,040 WARN  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0357: Notification of type deployment-undeployed is not described for the resource at the address []
00:16:48,041 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0009: Undeployed "jsf-chat.war" (runtime-name: "jsf-chat.war")
00:16:48,041 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."jsf-chat.war".POST_MODULE

00:16:52,839 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found jsf-chat.war in deployment directory. To trigger deployment create a file called jsf-chat.war.dodeploy

I tried to fix that by doing a lot of things but it still shows that error, I hope you can tell me how to fix it ...

**Comment by marlon-ulloa** [comment]
I solved it, but I have a new problem.. when redirect to chat-room.. shows the following error:

javax.servlet.ServletException: /char-room.xhtml @41,125 <f:websocket> Tag Library supports namespace: http://java.sun.com/jsf/core, but no tag was defined for name: websocket

I added the servlet api, jsf api... faces api... and many others in maven repository as dependencies but i still having the same error..... can you help me to solve that?

**Comment by wesleyegberto** [comment]
Hi
Sorry for the delay, I will take a look in the weekend.

**Comment by wesleyegberto** [comment]
Hi, have you tried to run on Wildfly 13 (using flag `ee8.preview.mode=true`) or Payara 5?
Feel free to reopen it.
