### ISSUE TITLE
clock: wildfly 13 error

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [wesleyegberto/javaee8-jsf-chat#2]
stack trace:
```
15:35:45,171 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-1) /chat-room.xhtml @68,108 listener="#{chatController.updateClock()}": java.lang.IllegalArgumentException: Cannot invoke getter of property 'annotatedOwnerType' of bean 'class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl'.: javax.el.ELException: /chat-room.xhtml @68,108 listener="#{chatController.updateClock()}": java.lang.IllegalArgumentException: Cannot invoke getter of property 'annotatedOwnerType' of bean 'class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl'.
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:113)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.facelets.tag.jsf.core.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxHandler.java:442)
	at javax.faces.api@2.3.5.SP1//javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:124)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:106)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:830)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:870)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1418)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.api@2.3.5.SP1//javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.0.9.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:171)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.9.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.core@2.0.9.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalArgumentException: Cannot invoke getter of property 'annotatedOwnerType' of bean 'class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl'.
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:363)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeArray(Json.java:286)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:183)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:140)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:124)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketSessionManager.send(WebsocketSessionManager.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketSessionManager$Proxy$_$$_WeldClientProxy.send(Unknown Source)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketPushContext.send(WebsocketPushContext.java:106)
	at deployment.jsf-chat.war//com.github.wesleyegberto.adoptajsr.jsfchat.controller.ChatController.updateClock(ChatController.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javax.el.api@1.0.11.Final//javax.el.ELUtil.invokeMethod(ELUtil.java:311)
	at javax.el.api@1.0.11.Final//javax.el.BeanELResolver.invoke(BeanELResolver.java:415)
	at javax.el.api@1.0.11.Final//javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.parser.AstValue.invoke(AstValue.java:285)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:107)
	... 57 more
	Suppressed: javax.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.close(JsonGeneratorImpl.java:531)
		at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:142)
		... 82 more
Caused by: java.lang.IllegalAccessException: class com.sun.faces.util.Json cannot access a member of class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl (in module java.base) with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:360)
	... 92 more

15:35:45,179 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-1) java.lang.IllegalArgumentException: Cannot invoke getter of property 'annotatedOwnerType' of bean 'class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl'.
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:363)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeArray(Json.java:286)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:183)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:367)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:192)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:140)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:124)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketSessionManager.send(WebsocketSessionManager.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketSessionManager$Proxy$_$$_WeldClientProxy.send(Unknown Source)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.push.WebsocketPushContext.send(WebsocketPushContext.java:106)
	at deployment.jsf-chat.war//com.github.wesleyegberto.adoptajsr.jsfchat.controller.ChatController.updateClock(ChatController.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javax.el.api@1.0.11.Final//javax.el.ELUtil.invokeMethod(ELUtil.java:311)
	at javax.el.api@1.0.11.Final//javax.el.BeanELResolver.invoke(BeanELResolver.java:415)
	at javax.el.api@1.0.11.Final//javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.parser.AstValue.invoke(AstValue.java:285)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.core@3.0.4.Final//org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:107)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.facelets.tag.jsf.core.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxHandler.java:442)
	at javax.faces.api@2.3.5.SP1//javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:124)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:106)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:830)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:870)
	at javax.faces.api@2.3.5.SP1//javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1418)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.api@2.3.5.SP1//javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.0.9.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:171)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.9.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.9.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow@14.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.9.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.9.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.core@2.0.9.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.base/java.lang.Thread.run(Thread.java:844)
	Suppressed: javax.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.close(JsonGeneratorImpl.java:531)
		at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encode(Json.java:142)
		... 82 more
Caused by: java.lang.IllegalAccessException: class com.sun.faces.util.Json cannot access a member of class sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl (in module java.base) with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at com.sun.jsf-impl@2.3.5.SP1//com.sun.faces.util.Json.encodeBean(Json.java:360)
	... 92 more

```

**Comment by wesleyegberto** [comment]
Just commited a fix.
The LocalDateTime couldn't be serialized, I will check the status about Java 8's new types support on Wildfly.
